# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name:  Python cicd
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# permissions:
#   contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
    - name: Run tests
      run: |
        python -m unittest discover
  slackNotification:
      name: Slack Notification
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v2
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Post Content :rocket:'
            SLACK_TITLE: Post Title
            SLACK_USERNAME: rtCamp
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  # slackNotification:
  #         runs-on: ubuntu-latest
  #         name: slacknotification
  #         needs: test
  #         #if: github.ref! = 'refs/heads/production'
  #         steps:
  #         - uses: actions/checkout@v3
  #         - name: notificationsdata
  #           uses: rtCamp/action-slack-notify@v2
  #           env:
  #              SLACK_WEBHOOK: https://hooks.slack.com/services/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
